### ISSUE TITLE
[MkDocs][Mobile] Second level submenus in navigation bar should be expandable by clicking or tapping.

### ISSUE THREAD

**Issue by vmaxim** [appium/appium.io#107]
### Env:
Platform: **Android 5.0.1**
Browser: **Chrome 61.0**

![screenrec](https://user-images.githubusercontent.com/3530074/31391462-483edec4-addf-11e7-88aa-136aae8c7484.gif)

**Comment by jlipps** [comment]
yes good point, @vmaxim. We'll have to ensure this works on mobile. Thanks for the repro gif :-)

**Comment by dpgraham** [comment]
Fixed by Isaac
