### ISSUE TITLE
[MkDocs][Mobile] Submenus of the second level or deeper should have indentation or differ style.

### ISSUE THREAD

**Issue by vmaxim** [appium/appium.io#108]
### Env:
Platform: **Android 5.0.1**
Browser: **Chrome 61.0**

![rundll32_2017-10-11_08-43-23](https://user-images.githubusercontent.com/3530074/31423999-88373176-ae60-11e7-9cb5-fb91286997e7.png)

**Comment by mykola-mokhnach** [comment]
@vmaxim Can you please share your email, so I can send you an invitation to Appium slack?

**Comment by vmaxim** [comment]
@mykola-mokhnach You can find it [here](https://api.github.com/users/vmaxim/events/public).

**Comment by imurchie** [comment]
This has been fixed (not deployed to that site, though).
