### ISSUE TITLE
Should update theme configuration to follow MkDocs 0.17.0

### ISSUE THREAD

**Issue by setoelkahfi** [appium/appium.io#114]
Currently
`theme: {{themeDir}}`

It should be
```
theme:
  name: cinder
  custom_dir: {{themeDir}}
```

[Release note](http://www.mkdocs.org/about/release-notes/#theme-customization-1164)

**Comment by jlipps** [comment]
thanks for letting us know! cc @dpgraham

**Comment by KazuCocoa** [comment]
Working on this in https://github.com/appium/appium.io/issues/225
