### ISSUE TITLE
Opening the tutorial returns a 404 Error

### ISSUE THREAD

**Issue by moijes12** [appium/appium.io#119]
Hi 

I am unable to view the Appium tutorials using the links on the appium.io homepage. Below are the steps I performed:

* Open the page http://appium.io/tutorial.html in Chrome on Mac
* Click on button 'Native Android Automation Tutorial'

Result:
* A 404 Error (see the attached screenshot)
![screen shot 2018-02-27 at 8 20 21 am](https://user-images.githubusercontent.com/4566851/36708128-922c3e98-1b97-11e8-887e-68b14b38379f.png)

**Comment by dpgraham** [comment]
This should be resolved. We use a link checker to verify that there's no 404's.

Please let me know if this is still an issue and I'll re-open.
