### ISSUE TITLE
Linking to Drivers on getting started is broken

### ISSUE THREAD

**Issue by megantfanning** [appium/appium.io#154]
the links for all the drivers in the 'getting started page' are incorrectly linked.

For example  UI Automator 2 inapproperiately links to https://appium.readthedocs.io/docs/en/drivers/android-uiautomator2.md (not a valid page) rather than https://appium.readthedocs.io/en/stable/en/drivers/android-uiautomator2/ please update and redirect.

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/ is the official one.

Maybe, the page is outdated site.
