### ISSUE TITLE
cannot bundle install

### ISSUE THREAD

**Issue by boneskull** [appium/appium.io#380]
1. `bundle install` tells me I need to `sudo bundle install` and then complains if I use `sudo`.
2. Whatever; running it anyway results in the huge error attached.

I think I'm using the system Ruby install, which:

- `ruby`: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
- `gem`: 3.0.3.1
- `bundle`: Bundler version 2.3.25

[bundle-error.txt](https://github.com/appium/appium.io/files/9923893/bundle-error.txt)

Further, the `README.md` references two different versions of `mkdocs`.  I was able to run the `build:docs:local` script, but could not run `serve` due to a missing `jekyll` (due to the problems noted above).

**Comment by KazuCocoa** [comment]
hm... the bundle install failed in the native extension's installation. I guess it was not good for m1 mac. (I only experienced intel one)

mkdocs can be `0.17.5`. Maybe I missed update the version to 0.17.5 after https://github.com/appium/appium.io/pull/316


Let me check the bundle install one tonight

**Comment by KazuCocoa** [comment]
Similar error in building `commonmarker 0.23.6` occurred with system installed ruby in macOS 10.15.7.
I usually use Ruby over `rbenv`, so haven't met such issues...
(Btw, macOS preinstalled Ruby is old, and had some issues in the past, so not recommended)
