### ISSUE TITLE
http://appium.io/get-involved.html?lang=en page issue

### ISSUE THREAD

**Issue by vikramvi** [appium/appium.io#60]
http://appium.io/get-involved.html?lang=en

clicking on Contributing Projects takes to 

http://appium.io/slate/en/master/?ruby#credits.md which has got heading "About Appium"
this is confusing

please check

thanks & regards,
Vikram

**Comment by jvanderwee** [comment]
Can [contributing.md](https://github.com/appium/appium.io/blob/gh-pages/contributing.md) be removed from the [_config.yml](https://github.com/appium/appium.io/blob/gh-pages/_config.yml) exclusions?

**Comment by jlipps** [comment]
thanks, this has been fixed with the correct link
