### ISSUE TITLE
Example Python code for Automating Hybrid Apps does not work

### ISSUE THREAD

**Issue by Menardi** [appium/appium.io#89]
The Python code at http://appium.io/slate/en/master/?python#automating-hybrid-apps is not valid Python. It appears to be closer to Ruby. I was going to submit a PR, but the only file I can find on here is `slate/master/en/index.html`, which looks auto-generated.

Here is my suggested Python code for that section. I am happy to create a PR if I could be pointed to the right file.

```
# python
# assuming we have an initialized `driver` object for an app

# switch to webview
webview = driver.contexts[-1]
driver.switch_to.context(webview)

# do some webby stuff
driver.find_elements_by_css_selector('.green_button')[0].click()

# switch back to native view
driver.switch_to.context(driver.contexts[0])

# do more native testing if we want

driver.quit()
```

**Comment by jlipps** [comment]
@Menardi thanks. Files are in the main appium repo under 'docs' if you'd like to submit a PR there!
