### ISSUE TITLE
Allow to switch to English on landing page when content is translated

### ISSUE THREAD

**Issue by hogmoru** [appium/appium.io#95]
My system language is French and it seems appium.io picks up on that info and offers me translated content of very poor quality. Please don't. Or at the very least let me switch to English.

For example, those bits are ridiculous:

> Introduisant Appium.
> Manquez-vous l'automatisation d'applications natives dans votre boîte à outils ? Problème résolu !

Thanks

**Comment by jlipps** [comment]
@hogmoru we're working on a revamp of the website and will be doing away with those translations. i think they are crowd-sourced so that probably accounts for the poor quality.

**Comment by hogmoru** [comment]
@jlipps Thanks for the reply, glad about your plans, won't mind if you close this issue in anticipation :)

**Comment by jlipps** [comment]
thanks! will close as we're tracking docs improvements here: https://github.com/appium/appium/issues/9136
